# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatTodoAppWithFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatTodoAppWithFirebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Nuke'
  pod 'PKHUD'
  
  target 'ChatTodoAppWithFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatTodoAppWithFirebaseUITests' do
    # Pods for testing
  end

end
